### ISSUE TITLE
How to create new scenario .xml files

### ISSUE THREAD

**Issue by liuqi8827** [RGring/drl_local_planner_ros_stable_baselines#7]
Hi 
Thanks for your work.

Is there any way to create new **scenario xml** files?
 (for example, the **pedsim_scenario.xml** file in your project)

Thanks a lot!

**Comment by RGring** [comment]
Hi liuqi8827,
You simulate a new environment by having an image of your map (*.png) combined with the map.yaml file. The pedsim_scneario.xml defines obstacles especially for the pedestrians. So all obstacles you define there, affect the pedestrian behaviour, because the potential field (wall force) gets more complex. Those obstacles, I defined manually. Be aware, the more complex the pedesim_sceario.xml gets, the more often a pedestrians ends up in a local minimum.

**Comment by liuqi8827** [comment]
Yes, I get it.
Thanks again.
