### ISSUE TITLE
 modified diff_drive-plugin 

### ISSUE THREAD

**Issue by kuroko1789** [RGring/drl_local_planner_ros_stable_baselines#8]
Hi, 
thanks for your work. I have read your Master Thesis, there is a modified diff_drive-plugin, where can I find the corresponding code?
Thanks a lot!

**Comment by RGring** [comment]
You define the plugin in a config, e.g. like in flatland_setup/robot/robot1.model. Else the repo is dependent on a forked version of flatland, because I made some performance optimizations regarding the DRL training: https://github.com/RGring/flatland/tree/pedsim_integration. You can sync the fork with the original repo on master and try to merge it into the branch pedsim_integration. Give some feedback, if it works. Feel free to make a pull request.
